update readme and add .gitignore file
alphagov/pay-admin-dashboard pull request #2
Opened 2016-11-21 10:33 UTC by wokoci

Added missing .gitignore file and update the readme to be more specific to how to setup and use application.

2016-11-23 15:04 UTC, ckalista requested changes

2016-11-23 15:04 UTC, ckalista commented on README.md
> +2. Open a terminal and execute `export NODE_CONFIG NODE_CONFIG='{"client": {"gitHub": {"accessToken": "XXXXXXXXXXXXXXXXXXXXXXXXc2XXXXeaXXXX9XX"}, "jenkins": {"deployParamBuildUrl": "https://deploy.de
Can you specify here that the accessToken XXX should be substituted.

2016-11-24 10:26 UTC, wokoci commented
Changes effected

2016-11-24 10:54 UTC, ckalista approved these changes
Code review completed.

2016-11-24 10:54 UTC, merged