add user avatar to application page
alphagov/pay-admin-dashboard pull request #5
Opened 2016-12-22 14:42 UTC by wokoci

Just added the developer avatar to the app page

2016-12-23 18:42 UTC, ckalista requested changes

2016-12-23 18:42 UTC, ckalista commented on views/releases-pipeline.html
>      </body>
Maybe there is no need to reformat here? Also there are not needed blank spaces...

2016-12-23 19:09 UTC, ckalista commented
Two additional comments: 
- The avatar should be alined on the lefthand side of the header.
- The avatar size should be such as the overall header width doesn't increase.

Also can you push the newly generated JS artifact. Use the following command to generate it:
`npm run-script build`

2016-12-23 19:41 UTC, wokoci commented on views/releases-pipeline.html
>      </body>
Code reformated

2017-01-04 17:46 UTC, ckalista commented
Code review completed - looks good.

2017-01-04 17:46 UTC, ckalista approved these changes

2017-01-04 17:47 UTC, merged